server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html page.html;
    
    location / {
        try_files $uri $uri/ =404;
    }
    
    # Disable sendfile for Windows Docker compatibility
    sendfile off;
}